namespace SpaLNT.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class DeleteNullableFK : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.BookingDetails", "BookingServiceId", "dbo.BookingServices");
            DropForeignKey("dbo.BookingDetails", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.BookingDetails", "UseServiceId", "dbo.UseServices");
            DropForeignKey("dbo.BookingServices", "CustomerId", "dbo.Customers");
            DropForeignKey("dbo.CustomerOrderDetails", "OrderCustomerId", "dbo.OrderCustomers");
            DropForeignKey("dbo.CustomerOrderDetails", "ProductDetailId", "dbo.ProductDetails");
            DropForeignKey("dbo.ProductDetails", "BranchId", "dbo.Branches");
            DropForeignKey("dbo.ProductDetails", "ProductId", "dbo.Products");
            DropForeignKey("dbo.ProviderOrderDetails", "ProductDetailId", "dbo.ProductDetails");
            DropForeignKey("dbo.Employees", "BranchId", "dbo.Branches");
            DropForeignKey("dbo.UseServices", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.Products", "FactoryId", "dbo.Factories");
            DropForeignKey("dbo.Products", "ProviderId", "dbo.Providers");
            DropForeignKey("dbo.Products", "TypeId", "dbo.Types");
            DropForeignKey("dbo.ProviderOrderDetails", "OrderProviderId", "dbo.OrderProviders");
            DropIndex("dbo.BookingDetails", new[] { "BookingServiceId" });
            DropIndex("dbo.BookingDetails", new[] { "ServiceId" });
            DropIndex("dbo.BookingDetails", new[] { "UseServiceId" });
            DropIndex("dbo.BookingServices", new[] { "CustomerId" });
            DropIndex("dbo.CustomerOrderDetails", new[] { "OrderCustomerId" });
            DropIndex("dbo.CustomerOrderDetails", new[] { "ProductDetailId" });
            DropIndex("dbo.ProductDetails", new[] { "ProductId" });
            DropIndex("dbo.ProductDetails", new[] { "BranchId" });
            DropIndex("dbo.Employees", new[] { "BranchId" });
            DropIndex("dbo.UseServices", new[] { "EmployeeId" });
            DropIndex("dbo.Products", new[] { "TypeId" });
            DropIndex("dbo.Products", new[] { "FactoryId" });
            DropIndex("dbo.Products", new[] { "ProviderId" });
            DropIndex("dbo.ProviderOrderDetails", new[] { "OrderProviderId" });
            DropIndex("dbo.ProviderOrderDetails", new[] { "ProductDetailId" });
            AlterColumn("dbo.BookingDetails", "BookingServiceId", c => c.Int(nullable: false));
            AlterColumn("dbo.BookingDetails", "ServiceId", c => c.Int(nullable: false));
            AlterColumn("dbo.BookingDetails", "UseServiceId", c => c.Int(nullable: false));
            AlterColumn("dbo.BookingServices", "CustomerId", c => c.Int(nullable: false));
            AlterColumn("dbo.CustomerOrderDetails", "OrderCustomerId", c => c.Int(nullable: false));
            AlterColumn("dbo.CustomerOrderDetails", "ProductDetailId", c => c.Int(nullable: false));
            AlterColumn("dbo.ProductDetails", "ProductId", c => c.Int(nullable: false));
            AlterColumn("dbo.ProductDetails", "BranchId", c => c.Int(nullable: false));
            AlterColumn("dbo.Employees", "BranchId", c => c.Int(nullable: false));
            AlterColumn("dbo.UseServices", "EmployeeId", c => c.Int(nullable: false));
            AlterColumn("dbo.Products", "TypeId", c => c.Int(nullable: false));
            AlterColumn("dbo.Products", "FactoryId", c => c.Int(nullable: false));
            AlterColumn("dbo.Products", "ProviderId", c => c.Int(nullable: false));
            AlterColumn("dbo.ProviderOrderDetails", "OrderProviderId", c => c.Int(nullable: false));
            AlterColumn("dbo.ProviderOrderDetails", "ProductDetailId", c => c.Int(nullable: false));
            CreateIndex("dbo.BookingDetails", "BookingServiceId");
            CreateIndex("dbo.BookingDetails", "ServiceId");
            CreateIndex("dbo.BookingDetails", "UseServiceId");
            CreateIndex("dbo.BookingServices", "CustomerId");
            CreateIndex("dbo.CustomerOrderDetails", "OrderCustomerId");
            CreateIndex("dbo.CustomerOrderDetails", "ProductDetailId");
            CreateIndex("dbo.ProductDetails", "ProductId");
            CreateIndex("dbo.ProductDetails", "BranchId");
            CreateIndex("dbo.Employees", "BranchId");
            CreateIndex("dbo.UseServices", "EmployeeId");
            CreateIndex("dbo.Products", "TypeId");
            CreateIndex("dbo.Products", "FactoryId");
            CreateIndex("dbo.Products", "ProviderId");
            CreateIndex("dbo.ProviderOrderDetails", "OrderProviderId");
            CreateIndex("dbo.ProviderOrderDetails", "ProductDetailId");
            AddForeignKey("dbo.BookingDetails", "BookingServiceId", "dbo.BookingServices", "Id", cascadeDelete: true);
            AddForeignKey("dbo.BookingDetails", "ServiceId", "dbo.Services", "Id", cascadeDelete: true);
            AddForeignKey("dbo.BookingDetails", "UseServiceId", "dbo.UseServices", "Id", cascadeDelete: true);
            AddForeignKey("dbo.BookingServices", "CustomerId", "dbo.Customers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CustomerOrderDetails", "OrderCustomerId", "dbo.OrderCustomers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CustomerOrderDetails", "ProductDetailId", "dbo.ProductDetails", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ProductDetails", "BranchId", "dbo.Branches", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ProductDetails", "ProductId", "dbo.Products", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ProviderOrderDetails", "ProductDetailId", "dbo.ProductDetails", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Employees", "BranchId", "dbo.Branches", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UseServices", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Products", "FactoryId", "dbo.Factories", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Products", "ProviderId", "dbo.Providers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Products", "TypeId", "dbo.Types", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ProviderOrderDetails", "OrderProviderId", "dbo.OrderProviders", "Id", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.ProviderOrderDetails", "OrderProviderId", "dbo.OrderProviders");
            DropForeignKey("dbo.Products", "TypeId", "dbo.Types");
            DropForeignKey("dbo.Products", "ProviderId", "dbo.Providers");
            DropForeignKey("dbo.Products", "FactoryId", "dbo.Factories");
            DropForeignKey("dbo.UseServices", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.Employees", "BranchId", "dbo.Branches");
            DropForeignKey("dbo.ProviderOrderDetails", "ProductDetailId", "dbo.ProductDetails");
            DropForeignKey("dbo.ProductDetails", "ProductId", "dbo.Products");
            DropForeignKey("dbo.ProductDetails", "BranchId", "dbo.Branches");
            DropForeignKey("dbo.CustomerOrderDetails", "ProductDetailId", "dbo.ProductDetails");
            DropForeignKey("dbo.CustomerOrderDetails", "OrderCustomerId", "dbo.OrderCustomers");
            DropForeignKey("dbo.BookingServices", "CustomerId", "dbo.Customers");
            DropForeignKey("dbo.BookingDetails", "UseServiceId", "dbo.UseServices");
            DropForeignKey("dbo.BookingDetails", "ServiceId", "dbo.Services");
            DropForeignKey("dbo.BookingDetails", "BookingServiceId", "dbo.BookingServices");
            DropIndex("dbo.ProviderOrderDetails", new[] { "ProductDetailId" });
            DropIndex("dbo.ProviderOrderDetails", new[] { "OrderProviderId" });
            DropIndex("dbo.Products", new[] { "ProviderId" });
            DropIndex("dbo.Products", new[] { "FactoryId" });
            DropIndex("dbo.Products", new[] { "TypeId" });
            DropIndex("dbo.UseServices", new[] { "EmployeeId" });
            DropIndex("dbo.Employees", new[] { "BranchId" });
            DropIndex("dbo.ProductDetails", new[] { "BranchId" });
            DropIndex("dbo.ProductDetails", new[] { "ProductId" });
            DropIndex("dbo.CustomerOrderDetails", new[] { "ProductDetailId" });
            DropIndex("dbo.CustomerOrderDetails", new[] { "OrderCustomerId" });
            DropIndex("dbo.BookingServices", new[] { "CustomerId" });
            DropIndex("dbo.BookingDetails", new[] { "UseServiceId" });
            DropIndex("dbo.BookingDetails", new[] { "ServiceId" });
            DropIndex("dbo.BookingDetails", new[] { "BookingServiceId" });
            AlterColumn("dbo.ProviderOrderDetails", "ProductDetailId", c => c.Int());
            AlterColumn("dbo.ProviderOrderDetails", "OrderProviderId", c => c.Int());
            AlterColumn("dbo.Products", "ProviderId", c => c.Int());
            AlterColumn("dbo.Products", "FactoryId", c => c.Int());
            AlterColumn("dbo.Products", "TypeId", c => c.Int());
            AlterColumn("dbo.UseServices", "EmployeeId", c => c.Int());
            AlterColumn("dbo.Employees", "BranchId", c => c.Int());
            AlterColumn("dbo.ProductDetails", "BranchId", c => c.Int());
            AlterColumn("dbo.ProductDetails", "ProductId", c => c.Int());
            AlterColumn("dbo.CustomerOrderDetails", "ProductDetailId", c => c.Int());
            AlterColumn("dbo.CustomerOrderDetails", "OrderCustomerId", c => c.Int());
            AlterColumn("dbo.BookingServices", "CustomerId", c => c.Int());
            AlterColumn("dbo.BookingDetails", "UseServiceId", c => c.Int());
            AlterColumn("dbo.BookingDetails", "ServiceId", c => c.Int());
            AlterColumn("dbo.BookingDetails", "BookingServiceId", c => c.Int());
            CreateIndex("dbo.ProviderOrderDetails", "ProductDetailId");
            CreateIndex("dbo.ProviderOrderDetails", "OrderProviderId");
            CreateIndex("dbo.Products", "ProviderId");
            CreateIndex("dbo.Products", "FactoryId");
            CreateIndex("dbo.Products", "TypeId");
            CreateIndex("dbo.UseServices", "EmployeeId");
            CreateIndex("dbo.Employees", "BranchId");
            CreateIndex("dbo.ProductDetails", "BranchId");
            CreateIndex("dbo.ProductDetails", "ProductId");
            CreateIndex("dbo.CustomerOrderDetails", "ProductDetailId");
            CreateIndex("dbo.CustomerOrderDetails", "OrderCustomerId");
            CreateIndex("dbo.BookingServices", "CustomerId");
            CreateIndex("dbo.BookingDetails", "UseServiceId");
            CreateIndex("dbo.BookingDetails", "ServiceId");
            CreateIndex("dbo.BookingDetails", "BookingServiceId");
            AddForeignKey("dbo.ProviderOrderDetails", "OrderProviderId", "dbo.OrderProviders", "Id");
            AddForeignKey("dbo.Products", "TypeId", "dbo.Types", "Id");
            AddForeignKey("dbo.Products", "ProviderId", "dbo.Providers", "Id");
            AddForeignKey("dbo.Products", "FactoryId", "dbo.Factories", "Id");
            AddForeignKey("dbo.UseServices", "EmployeeId", "dbo.Employees", "Id");
            AddForeignKey("dbo.Employees", "BranchId", "dbo.Branches", "Id");
            AddForeignKey("dbo.ProviderOrderDetails", "ProductDetailId", "dbo.ProductDetails", "Id");
            AddForeignKey("dbo.ProductDetails", "ProductId", "dbo.Products", "Id");
            AddForeignKey("dbo.ProductDetails", "BranchId", "dbo.Branches", "Id");
            AddForeignKey("dbo.CustomerOrderDetails", "ProductDetailId", "dbo.ProductDetails", "Id");
            AddForeignKey("dbo.CustomerOrderDetails", "OrderCustomerId", "dbo.OrderCustomers", "Id");
            AddForeignKey("dbo.BookingServices", "CustomerId", "dbo.Customers", "Id");
            AddForeignKey("dbo.BookingDetails", "UseServiceId", "dbo.UseServices", "Id");
            AddForeignKey("dbo.BookingDetails", "ServiceId", "dbo.Services", "Id");
            AddForeignKey("dbo.BookingDetails", "BookingServiceId", "dbo.BookingServices", "Id");
        }
    }
}
