// <auto-generated />
namespace SpaLNT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddFK_OrderProvider_Branch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFK_OrderProvider_Branch));
        
        string IMigrationMetadata.Id
        {
            get { return "202202100946037_Add FK_OrderProvider_Branch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
